### ISSUE TITLE
Merge PlaceholderExpansion and EZPlaceholderHook together

### ISSUE THREAD

**Issue by games647** [extendedclip/PlaceholderAPI#2]
We look nearly the same. So it would make sense to make a more universal version of it. Plugins that need to check for the placeholder name need to check for both cases although they are so much the same. 

In order to not make break existing plugins using this API, I would suggest to just remove the internal used class PlaceholderExpansion and replace it EZPlaceholderHook.

**Comment by extendedclip** [comment]
Sorry for the late response....

EZPlaceholderHook purpose is for registering placeholders from an external plugin which includes the class which extends EZPlaceholderHook within the external plugin. EZPlaceholderHook is essentially just an extension of PlaceholderHook (which is required to register a placeholder) that provides more easy access methods for the placeholder developer.

PlaceholderExpansion is specifically for placeholder expansion jars as PlaceholderAPI class loading system searches the expansions directory for classes within the present jar files that extend PlaceholderExpansion. I know it may seem a bit redundant to have both but PlaceholderAPI utilizes both classes in different ways.
