### ISSUE TITLE
Placeholder api will popup an error if Protocollib is not installed

### ISSUE THREAD

**Issue by xion87** [extendedclip/PlaceholderAPI#4]
Hi, i dont know why placeholderapi popup this error at startup: https://hastebin.com/anuzilazuw.vbs
But if i install protocollib it fix it, i am using papi 2.6.0 and spigot 1.8.8
Ps that error is not causing any issue to plugin functionality. And yes i am using chat injector

**Comment by extendedclip** [comment]
This should be fixed in 2.7.0
